/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo2;

import javax.swing.JOptionPane;

/**
 *
 * @author yaret
 */
public class Banco extends javax.swing.JFrame {

    Cliente datos;

    /**
     * Creates new form Banco
     */
    public Banco() {

        initComponents();
        datos= new Cliente();
        datos.conectar();
        jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
        DepositoDeCuenta.setVisible(false);
        Modificaciones.setVisible(false);
        Cancelacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreacionDeCuenta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCrear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoCrear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreoCrear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOcupacionCrear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefonoCrear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMontoICrear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMinimoRCrear = new javax.swing.JTextField();
        btnGuardarCrear = new javax.swing.JButton();
        btnLimpiarCrear = new javax.swing.JButton();
        btnRegresarCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCrearCuenta = new javax.swing.JButton();
        btnConsultaCuenta = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnModificaciones = new javax.swing.JButton();
        btnCancelacionCuenta = new javax.swing.JButton();
        ConsultaDeCuenta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtCorreoConsulta = new javax.swing.JTextField();
        btnConsultaC = new javax.swing.JButton();
        btnLimpiarConsulta = new javax.swing.JButton();
        btnRegresarConsulta = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        RetiroDeCuenta = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        DepositoDeCuenta = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCorreoDeposito = new javax.swing.JTextField();
        txtMontoDDeposito = new javax.swing.JTextField();
        btnRegresarDesposito = new javax.swing.JButton();
        btnDepositarD = new javax.swing.JButton();
        Modificaciones = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCorreoM = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtCorreoMM = new javax.swing.JTextField();
        txtOcupacionM = new javax.swing.JTextField();
        txtTelefonoM = new javax.swing.JTextField();
        txtMontoM = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        Cancelacion = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtCorreoC = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreacionDeCuenta.setName("Altas"); // NOI18N

        jLabel1.setText("Creacion de cuenta");

        jLabel2.setText("Nombre");

        txtNombreCrear.setName("txtNombre"); // NOI18N
        txtNombreCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCrearActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        txtApellidoCrear.setName("txtApellido"); // NOI18N
        txtApellidoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCrearActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo");

        txtCorreoCrear.setName("txtCorreo"); // NOI18N

        jLabel5.setText("Ocupacion");

        txtOcupacionCrear.setName("txtOcupacion"); // NOI18N

        jLabel6.setText("Telefono");

        txtTelefonoCrear.setName("txtTelefono"); // NOI18N

        jLabel7.setText("Monto inicial");

        txtMontoICrear.setName("txtMontoInicial"); // NOI18N
        txtMontoICrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoICrearActionPerformed(evt);
            }
        });
        txtMontoICrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoICrearKeyTyped(evt);
            }
        });

        jLabel8.setText("Minimo a retirar");

        txtMinimoRCrear.setName("txtMinimoRetiro"); // NOI18N
        txtMinimoRCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinimoRCrearKeyTyped(evt);
            }
        });

        btnGuardarCrear.setText("Guardar");
        btnGuardarCrear.setName("btnGuardarAltas"); // NOI18N
        btnGuardarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCrearActionPerformed(evt);
            }
        });

        btnLimpiarCrear.setText("Limpiar");
        btnLimpiarCrear.setName("btnLimpiar"); // NOI18N
        btnLimpiarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCrearActionPerformed(evt);
            }
        });

        btnRegresarCrear.setText("Regresar");
        btnRegresarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreacionDeCuentaLayout = new javax.swing.GroupLayout(CreacionDeCuenta);
        CreacionDeCuenta.setLayout(CreacionDeCuentaLayout);
        CreacionDeCuentaLayout.setHorizontalGroup(
            CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellidoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(txtCorreoCrear)
                                    .addComponent(txtNombreCrear)))))
                    .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                        .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                                .addComponent(btnRegresarCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiarCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreacionDeCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMontoICrear))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreacionDeCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtOcupacionCrear))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreacionDeCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMinimoRCrear)))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarCrear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreacionDeCuentaLayout.setVerticalGroup(
            CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeCuentaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOcupacionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMontoICrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMinimoRCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(CreacionDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.setName("btnAltas"); // NOI18N
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnConsultaCuenta.setText("Consulta de cuenta");
        btnConsultaCuenta.setName("btnConsultas"); // NOI18N
        btnConsultaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCuentaActionPerformed(evt);
            }
        });

        btnRetiro.setText("Retiro");
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });

        btnDeposito.setText("Deposito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        btnModificaciones.setText("Modificacion de datos");
        btnModificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionesActionPerformed(evt);
            }
        });

        btnCancelacionCuenta.setText("Cancelacion de cuenta");
        btnCancelacionCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelacionCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("Ingrese su correo");

        txtCorreoConsulta.setName("txtCo"); // NOI18N

        btnConsultaC.setText("Consultar cuenta");
        btnConsultaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCActionPerformed(evt);
            }
        });

        btnLimpiarConsulta.setText("Limpiar");
        btnLimpiarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarConsultaActionPerformed(evt);
            }
        });

        btnRegresarConsulta.setText("Regresar");
        btnRegresarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarConsultaActionPerformed(evt);
            }
        });

        jLabel10.setText("Consulta de cuenta");

        javax.swing.GroupLayout ConsultaDeCuentaLayout = new javax.swing.GroupLayout(ConsultaDeCuenta);
        ConsultaDeCuenta.setLayout(ConsultaDeCuentaLayout);
        ConsultaDeCuentaLayout.setHorizontalGroup(
            ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultaDeCuentaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(ConsultaDeCuentaLayout.createSequentialGroup()
                .addGroup(ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaDeCuentaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel10))
                    .addGroup(ConsultaDeCuentaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnRegresarConsulta)
                        .addGap(34, 34, 34)
                        .addComponent(btnLimpiarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultaC)))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        ConsultaDeCuentaLayout.setVerticalGroup(
            ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaDeCuentaLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addGroup(ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCorreoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConsultaDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultaC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegresarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel11.setText("Retiro de cuenta");

        jLabel12.setText("Ingrese su correo");

        jLabel13.setText("Monto a retirar");

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jButton13.setText("Retirar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Regresar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RetiroDeCuentaLayout = new javax.swing.GroupLayout(RetiroDeCuenta);
        RetiroDeCuenta.setLayout(RetiroDeCuentaLayout);
        RetiroDeCuentaLayout.setHorizontalGroup(
            RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel11))
                    .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                                .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(15, 15, 15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                                .addComponent(jButton14)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        RetiroDeCuentaLayout.setVerticalGroup(
            RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiroDeCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(34, 34, 34)
                .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(38, 38, 38)
                .addGroup(RetiroDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton13))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jLabel15.setText("Deposito a cuenta");

        jLabel16.setText("Ingrese su correo");

        jLabel17.setText("Monto a depositar");

        txtCorreoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoDepositoActionPerformed(evt);
            }
        });

        txtMontoDDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoDDepositoKeyTyped(evt);
            }
        });

        btnRegresarDesposito.setText("Regresar");
        btnRegresarDesposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDespositoActionPerformed(evt);
            }
        });

        btnDepositarD.setText("Depositar");
        btnDepositarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DepositoDeCuentaLayout = new javax.swing.GroupLayout(DepositoDeCuenta);
        DepositoDeCuenta.setLayout(DepositoDeCuentaLayout);
        DepositoDeCuentaLayout.setHorizontalGroup(
            DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositoDeCuentaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositoDeCuentaLayout.createSequentialGroup()
                        .addComponent(btnRegresarDesposito)
                        .addGap(49, 49, 49)
                        .addComponent(btnDepositarD)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DepositoDeCuentaLayout.createSequentialGroup()
                        .addGroup(DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMontoDDeposito)
                            .addComponent(txtCorreoDeposito))
                        .addGap(115, 115, 115))))
            .addGroup(DepositoDeCuentaLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel15)
                .addGap(121, 121, 121))
        );
        DepositoDeCuentaLayout.setVerticalGroup(
            DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositoDeCuentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DepositoDeCuentaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel16))
                    .addComponent(txtCorreoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtMontoDDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(DepositoDeCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarDesposito)
                    .addComponent(btnDepositarD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("Modificaciones");

        jLabel20.setText("Ingrese su correo");

        txtCorreoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoMActionPerformed(evt);
            }
        });

        jLabel21.setText("Modifique sus datos");

        jLabel22.setText("Nuevo nombre");

        jLabel23.setText("Nuevo apellido");

        jLabel24.setText("Nuevo correo");

        jLabel25.setText("Nueva ocupacion ");

        jLabel26.setText("Nuevo telefono ");

        jLabel27.setText("Nuevo monto de retiro ");

        txtMontoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoMKeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificacionesLayout = new javax.swing.GroupLayout(Modificaciones);
        Modificaciones.setLayout(ModificacionesLayout);
        ModificacionesLayout.setHorizontalGroup(
            ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificacionesLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ModificacionesLayout.createSequentialGroup()
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificacionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(txtCorreoMM)
                                .addComponent(txtOcupacionM)
                                .addComponent(txtTelefonoM)
                                .addComponent(txtNombreM))
                            .addComponent(txtMontoM, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificacionesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificacionesLayout.createSequentialGroup()
                        .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificacionesLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel21))
                            .addGroup(ModificacionesLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreoM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ModificacionesLayout.setVerticalGroup(
            ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCorreoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCorreoMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtOcupacionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnRegresar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel28.setText("Cancelacion de cuenta");

        jLabel29.setText("Ingrese su correo");

        btnCancelar.setText("Cancelar cuenta");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CancelacionLayout = new javax.swing.GroupLayout(Cancelacion);
        Cancelacion.setLayout(CancelacionLayout);
        CancelacionLayout.setHorizontalGroup(
            CancelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelacionLayout.createSequentialGroup()
                .addGroup(CancelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancelacionLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel28))
                    .addGroup(CancelacionLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(CancelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CancelacionLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addGroup(CancelacionLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(28, 28, 28)
                                .addComponent(txtCorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        CancelacionLayout.setVerticalGroup(
            CancelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel28)
                .addGap(23, 23, 23)
                .addGroup(CancelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtCorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(CancelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(jButton1))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CreacionDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsultaDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(RetiroDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(DepositoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Cancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(DepositoDeCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreacionDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RetiroDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        CreacionDeCuenta.setVisible(true);
        jPanel2.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
        DepositoDeCuenta.setVisible(false);
        Modificaciones.setVisible(false);
        Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
       CreacionDeCuenta.setVisible(false);
        jPanel2.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(true);
        DepositoDeCuenta.setVisible(false);
        Modificaciones.setVisible(false);
        Cancelacion.setVisible(false);
        
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void txtNombreCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCrearActionPerformed

    private void txtApellidoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCrearActionPerformed

    private void txtMontoICrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoICrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoICrearActionPerformed

    private void btnGuardarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCrearActionPerformed
        datos.altas(
                
                txtNombreCrear.getText(),
                txtApellidoCrear.getText(),
                txtCorreoCrear.getText(),
                txtOcupacionCrear.getText(),
                txtTelefonoCrear.getText(),
                txtMontoICrear.getText(),
                txtMinimoRCrear.getText());

        if(txtNombreCrear.getText().equals("") || txtApellidoCrear.getText().equals("") ||txtCorreoCrear.getText().equals("") ||
                txtOcupacionCrear.getText().equals("") ||txtTelefonoCrear.getText().equals("")|| txtMontoICrear.getText().equals("")
                || txtMinimoRCrear.getText().equals("")){
            
            JOptionPane.showMessageDialog(null,"Por favor ingrese los datos faltantes");
        }
        else{
            double montoI = Double.parseDouble(txtMontoICrear.getText());
            
            if(montoI>50)
            JOptionPane.showMessageDialog(null, "Los datos han sido guardados con éxito!");
        }
         
          
          
          
          

    }//GEN-LAST:event_btnGuardarCrearActionPerformed

    private void btnLimpiarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCrearActionPerformed
        txtNombreCrear.setText("");
        txtApellidoCrear.setText("");
        txtCorreoCrear.setText("");
        txtOcupacionCrear.setText("");
        txtTelefonoCrear.setText("");
        txtMontoICrear.setText("");
        txtMinimoRCrear.setText("");

    }//GEN-LAST:event_btnLimpiarCrearActionPerformed

    private void btnRegresarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCrearActionPerformed
        jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
         ConsultaDeCuenta.setVisible(false);
          RetiroDeCuenta.setVisible(false);
           DepositoDeCuenta.setVisible(false);
            Modificaciones.setVisible(false);
             Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnRegresarCrearActionPerformed

    private void btnConsultaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCuentaActionPerformed
        ConsultaDeCuenta.setVisible(true);
        jPanel2.setVisible(false);
        CreacionDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
         DepositoDeCuenta.setVisible(false);
          Modificaciones.setVisible(false);
           Cancelacion.setVisible(false);

    }//GEN-LAST:event_btnConsultaCuentaActionPerformed

    private void btnConsultaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCActionPerformed
      jTextArea1.setText(datos.consulta(txtCorreoConsulta.getText())); 
      if(txtCorreoConsulta.getText().equals("")){
          JOptionPane.showMessageDialog(null,"Por favor ingrese su correo");
          
      }

//        jTextArea1.append("Nombre:" + txtNombreCrear.getText() + "\n");
//        jTextArea1.append("Apellido:" + txtApellidoCrear.getText() + "\n");
//        jTextArea1.append("Correo:" + txtCorreoCrear.getText() + "\n");
//        jTextArea1.append("Ocupacion:" + txtOcupacionCrear.getText() + "\n");
//        jTextArea1.append("Telefono:" + txtTelefonoCrear.getText() + "\n");
//        jTextArea1.append("Monto Inicial:" + txtMontoICrear.getText() + "\n");
//        jTextArea1.append("Monto de retiro:" + txtMinimoRCrear.getText() + "\n");


    }//GEN-LAST:event_btnConsultaCActionPerformed

    private void btnLimpiarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarConsultaActionPerformed
        txtCorreoConsulta.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_btnLimpiarConsultaActionPerformed

    private void btnRegresarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarConsultaActionPerformed
        jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
         RetiroDeCuenta.setVisible(false);
          DepositoDeCuenta.setVisible(false);
           Modificaciones.setVisible(false);
            Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnRegresarConsultaActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        datos.retiro(jTextField9.getText(), jTextField10.getText());
if(jTextField9.getText().equals("") || jTextField10.getText().equals("") ){
          JOptionPane.showMessageDialog(null,"Ingrese los datos faltantes");
          
      }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
         DepositoDeCuenta.setVisible(false);
          Modificaciones.setVisible(false);
           Cancelacion.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void txtCorreoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoDepositoActionPerformed

    private void btnDepositarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarDActionPerformed
       datos.deposito(txtCorreoDeposito.getText(), txtMontoDDeposito.getText());
    }//GEN-LAST:event_btnDepositarDActionPerformed

    private void btnRegresarDespositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDespositoActionPerformed
        jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
         DepositoDeCuenta.setVisible(false);
          Modificaciones.setVisible(false);
           Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnRegresarDespositoActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
         CreacionDeCuenta.setVisible(false);
        jPanel2.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
        DepositoDeCuenta.setVisible(true);
        Modificaciones.setVisible(false);
         Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void txtCorreoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMActionPerformed

    private void btnModificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionesActionPerformed
      
        CreacionDeCuenta.setVisible(false);
        jPanel2.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
        DepositoDeCuenta.setVisible(false);
        Modificaciones.setVisible(true);
         Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnModificacionesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
         DepositoDeCuenta.setVisible(false);
          Modificaciones.setVisible(false);
           Cancelacion.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        datos.modificaciones(txtCorreoM.getText(),
                txtNombreM.getText(),
                txtApellidoM.getText(),
                txtCorreoMM.getText(),
                txtOcupacionM.getText(),
                txtTelefonoM.getText(),
                txtMontoM.getText());
                
        if(txtCorreoM.getText().equals("") || txtNombreM.getText().equals("") ||txtApellidoM.getText().equals("") ||
                txtCorreoMM.getText().equals("") ||txtOcupacionM.getText().equals("")|| txtTelefonoM.getText().equals("")
                || txtMontoM.getText().equals("")){
            
            JOptionPane.showMessageDialog(null,"Por favor ingrese los datos faltantes");
        }
        else{
            JOptionPane.showMessageDialog(null, "Los datos han sido guardados con éxito!");
        }       
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       datos.bajas(txtCorreoC.getText());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelacionCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelacionCuentaActionPerformed
        
         CreacionDeCuenta.setVisible(false);
        jPanel2.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
        DepositoDeCuenta.setVisible(false);
        Modificaciones.setVisible(false);
         Cancelacion.setVisible(true);
    }//GEN-LAST:event_btnCancelacionCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      jPanel2.setVisible(true);
        CreacionDeCuenta.setVisible(false);
        ConsultaDeCuenta.setVisible(false);
        RetiroDeCuenta.setVisible(false);
         DepositoDeCuenta.setVisible(false);
          Modificaciones.setVisible(false);
           Cancelacion.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMontoICrearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoICrearKeyTyped
      char validar=evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_txtMontoICrearKeyTyped

    private void txtMinimoRCrearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinimoRCrearKeyTyped
        char validar=evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_txtMinimoRCrearKeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
      char validar=evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void txtMontoDDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoDDepositoKeyTyped
       char validar=evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_txtMontoDDepositoKeyTyped

    private void txtMontoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoMKeyTyped
        char validar=evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
    }//GEN-LAST:event_txtMontoMKeyTyped
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cancelacion;
    private javax.swing.JPanel ConsultaDeCuenta;
    private javax.swing.JPanel CreacionDeCuenta;
    private javax.swing.JPanel DepositoDeCuenta;
    private javax.swing.JPanel Modificaciones;
    private javax.swing.JPanel RetiroDeCuenta;
    private javax.swing.JButton btnCancelacionCuenta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultaC;
    private javax.swing.JButton btnConsultaCuenta;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnDepositarD;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarCrear;
    private javax.swing.JButton btnLimpiarConsulta;
    private javax.swing.JButton btnLimpiarCrear;
    private javax.swing.JButton btnModificaciones;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresarConsulta;
    private javax.swing.JButton btnRegresarCrear;
    private javax.swing.JButton btnRegresarDesposito;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtApellidoCrear;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtCorreoC;
    private javax.swing.JTextField txtCorreoConsulta;
    private javax.swing.JTextField txtCorreoCrear;
    private javax.swing.JTextField txtCorreoDeposito;
    private javax.swing.JTextField txtCorreoM;
    private javax.swing.JTextField txtCorreoMM;
    private javax.swing.JTextField txtMinimoRCrear;
    private javax.swing.JTextField txtMontoDDeposito;
    private javax.swing.JTextField txtMontoICrear;
    private javax.swing.JTextField txtMontoM;
    private javax.swing.JTextField txtNombreCrear;
    private javax.swing.JTextField txtNombreM;
    private javax.swing.JTextField txtOcupacionCrear;
    private javax.swing.JTextField txtOcupacionM;
    private javax.swing.JTextField txtTelefonoCrear;
    private javax.swing.JTextField txtTelefonoM;
    // End of variables declaration//GEN-END:variables
}
